steps:
- name: 'gcr.io/cloud-builders/java/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=eu.gcr.io/$PROJECT_ID/spinnaker-demo:$BUILD_ID', '.']
images: ['eu.gcr.io/$PROJECT_ID/spinnaker-demo:$BUILD_ID']
