steps:
- name: 'gcr.io/cloud-builders/java/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/ageless-aquifer-234408/gcp-cd-codelab:$REVISION_ID", "-f", "Dockerfile", "."]
images: ["gcr.io/ageless-aquifer-234408/gcp-cd-codelab:$REVISION_ID"]
